"use client";
import { useState } from 'react';
import './globals.css'
import type { Metadata } from 'next'
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const client = new ApolloClient({
  uri: 'http://localhost:4000',
  cache: new InMemoryCache()
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [res, setRes] = useState();
  
  return (
    <html>
      <ApolloProvider client={client}>
      <body>{children}</body>
      </ApolloProvider>
    </html>
  )
}
