"use client";
import { useState } from 'react';
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [res, setRes] = useState();
  
  return (
    <html>
      <body>{children}</body>
    </html>
  )
}
